### PR TITLE
Implement Windows Directory structure

### PR DESCRIPTION
**Pull request by f3lang**
This implements the functions for the standard windows directory structure.
I tried to stick to the microsoft docs and the jsdoc of the project.
The tests are written according to the existing ones and all of them are working.

### CODE REVIEW

**Comment by f3lang** [comment]
The checks initially failed, because of the travis-ci server is running on a posix system and the path.join() joined the directories to something like "C:\Users\fakeuser\AppData/someApp". I have overridden the path.join method now for the tests with the path.win32.join to get the tests working under posix systems. 

But as i noticed, the path.win32 was added in node version 0.11 and the ci has also a configuration for 0.10, which fails.

**Comment by leedm777** [comment]
@f3lang Thanks for the patch!

On master, I've updated the Travis CI config to build on Node.js v4 and v6. If you rebase against master and can get the tests passing, I will very happily merge your PR.

**Comment by f3lang** [comment]
@leedm777 Thank you for the travis update!
I rebased, all tests are now up and running.

**Comment by leedm777** [comment]
Published in appdirs@1.1.0. Thanks!

**Pull request merged**
